/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/island.glb')
  return (
    <group {...props} dispose={null}>
      <mesh material-color={'red'} material-transparent={true} material-opacity={0.5} geometry={nodes.NavMesh_Exported_NavMesh.geometry} material={materials['Default OBJ']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.SM_Tile_Hex_FloatingIsland_01.geometry} material={materials.lambert101} position={[0.02, 0.46, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.SM_Bld_Pirate_Mansion_01.geometry} material={materials.lambert101} position={[1.09, 0, 0.61]} rotation={[Math.PI / 2, 0, 0.54]} scale={0.01} />
      <mesh geometry={nodes.SM_Bld_Pirate_Shack_01.geometry} material={materials.lambert101} position={[-1.33, 0, 1.09]} rotation={[Math.PI / 2, 0, -0.45]} scale={0.01} />
      <mesh geometry={nodes.SM_Bld_Pirates_Fountain_01.geometry} material={materials.lambert101} position={[-1.09, 0, -1.78]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.SM_Env_Pirate_Palm_01.geometry} material={materials.lambert101} position={[-1.87, 0, -0.96]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.SM_Env_Pirate_Palm_02.geometry} material={materials.lambert101} position={[0, 0, 0.78]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.SM_Env_Pirate_Palm_03.geometry} material={materials.lambert101} position={[1.22, 0, 2.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.SM_Env_Pirate_SkullRock_01.geometry} material={materials.lambert101} position={[1.09, 0, -1.7]} rotation={[Math.PI / 2, 0, 0.38]} scale={0.01} />
      <mesh geometry={nodes.navmesh.geometry} material={materials['Default OBJ.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/island.glb')
