import { Canvas } from '@react-three/fiber'
import Head from 'next/head'
import Image from 'next/image'
import { Suspense } from 'react'
import styles from '../styles/Home.module.css'
import Scene from './Scene'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ width: "100vw", height: "100vh" }}>
        <Canvas className={styles.canvas} shadows>
          <Suspense fallback={null}>
            <Scene />
          </Suspense>
        </Canvas>
       </main>
    </div>
  )
}
